-- Operations schema, Postgres version of 0001_initial.sql (schema `ops`): pipeline runs, their
-- steps, every outbound request, and the queue of discovered replay videos.
--
-- Same tables and columns. Differences: generated ids are identity columns; row level security
-- is on (no policies: only the owner, xg_pipeline, can read or write, and the schema is not
-- exposed through Supabase's Data API). Times stay ISO-8601 TEXT as in SQLite, except
-- requests.ts (unix seconds), which the rate limiter does arithmetic on.

CREATE TABLE runs (
    run_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trigger     TEXT NOT NULL,               -- schedule | manual | ui | cli
    command     TEXT NOT NULL,               -- run | discover | process | rebuild | ...
    args        TEXT,                        -- JSON
    started_at  TEXT NOT NULL,
    finished_at TEXT,
    status      TEXT NOT NULL,               -- running | ok | partial | failed
    git_commit  TEXT,
    pid         INTEGER,
    summary     TEXT                         -- JSON
);

CREATE TABLE steps (
    step_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id           BIGINT REFERENCES runs (run_id),
    stage            TEXT NOT NULL,          -- discover | transcript | game_data | align
    video_id         TEXT,
    game_id          BIGINT,
    started_at       TEXT NOT NULL,
    finished_at      TEXT,
    status           TEXT NOT NULL,          -- running | ok | skipped | failed
    error            TEXT,
    youtube_requests INTEGER DEFAULT 0
);
CREATE INDEX ix_steps_run ON steps (run_id);
CREATE INDEX ix_steps_video ON steps (video_id);  -- a video's history in the dashboard

-- Every outbound request, written by the rate limiter (it also reads this to space requests).
CREATE TABLE requests (
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts         DOUBLE PRECISION NOT NULL,    -- unix time when sent
    run_id     BIGINT,
    kind       TEXT NOT NULL,                -- yt_page | yt_caption | yt_frame | yt_api | nhl | moneypuck
    target     TEXT,
    status     TEXT,                         -- sent | ok | error | blocked
    latency_ms INTEGER
);
CREATE INDEX ix_requests_kind_ts ON requests (kind, ts);
CREATE INDEX ix_requests_run ON requests (run_id);

-- Replay videos found on YouTube, and how far each has been processed.
CREATE TABLE videos (
    video_id        TEXT PRIMARY KEY,
    title           TEXT,
    published_at    TEXT,
    discovered_at   TEXT,
    game_id         BIGINT,
    state           TEXT NOT NULL,           -- see pipeline.py
    attempts        INTEGER DEFAULT 0,
    last_error      TEXT,
    next_attempt_at TEXT,                    -- NULL = due now; 'never' = needs a manual fix
    updated_at      TEXT
);
CREATE INDEX ix_videos_state ON videos (state, published_at);

-- Small key/value state: rate-limiter cooldown, discovery progress.
CREATE TABLE kv (
    key   TEXT PRIMARY KEY,
    value TEXT
);

ALTER TABLE runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE videos ENABLE ROW LEVEL SECURITY;
ALTER TABLE kv ENABLE ROW LEVEL SECURITY;
